// <auto-generated />
using FluentApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FluentApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180511175504_AppStart")]
    partial class AppStart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FluentApi.Models.BuracoNegro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GalaxiaId");

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<double>("Tamanho");

                    b.HasKey("Id");

                    b.HasIndex("GalaxiaId");

                    b.ToTable("BuracosNegros");
                });

            modelBuilder.Entity("FluentApi.Models.Galaxia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<double>("Tamanho");

                    b.HasKey("Id");

                    b.ToTable("Galaxias");
                });

            modelBuilder.Entity("FluentApi.Models.Planeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GalaxiaId");

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<double>("Tamanho");

                    b.HasKey("Id");

                    b.HasIndex("GalaxiaId")
                        .IsUnique()
                        .HasFilter("[GalaxiaId] IS NOT NULL");

                    b.ToTable("Planetas");
                });

            modelBuilder.Entity("FluentApi.Models.BuracoNegro", b =>
                {
                    b.HasOne("FluentApi.Models.Galaxia", "Galaxia")
                        .WithMany("BuracoNegros")
                        .HasForeignKey("GalaxiaId");
                });

            modelBuilder.Entity("FluentApi.Models.Planeta", b =>
                {
                    b.HasOne("FluentApi.Models.Galaxia", "Galaxia")
                        .WithOne("Planeta")
                        .HasForeignKey("FluentApi.Models.Planeta", "GalaxiaId");
                });
#pragma warning restore 612, 618
        }
    }
}
